### PR TITLE
Rider Applications: Fix Rider Application Form and Added Show Page

### LINKED ISSUE #22: Rider Application: Fix Rider Application Form Fields and Rider Application Show Page
## Fields on RiderApplicationForm
* `id` (only if the rider has already applied; this should be labelled as `applicant id` on the form, but is just `id` internally)
* `status` this will be pre-populated with the status of the application: (pending for newly created applications) and will not be editable.  See status values below.
* `email` this will be pre-populated from the current user and will not be editable, but will appear
* `perm_number`  This field will be editable  and will accept the perm number.  Perm numbers are 7 characters, and are now alphanumeric (not just numeric).  
* `date applied` this will be pre-populated with the date the application was first created, and is not editable
* `date updated` this will be pre-populated with the date the application was last updated.
* `date cancelled`   this will be pre-populated with the date the application was cancelled (if and only if it was cancelled)
* `description` This will be an editable text field that should be, initially, the full width of the container and at least 6 lines of text high, and should be expandable.  It will be labelled with "Please describe the mobility limitations that cause you to need to use the Gauchoride service."
* `notes` This will be a text field that is not editable by the applicant, but will contain information entered by the admin that acts on the application.  This field is for communicating information back to the applicant about the status of their application.

# Task
- [x] The Rider Application Form had two fields: Application Id and Applicant Id. This implementation was wrong and should only have one field for ID which is the rider application ID. This ID can be found in the Rider Application Entities file. 
- [x] The email field the in the form should be auto populated with the current user's email. This was not the case prior.
- [x] Must fix the date update, applied, and cancelled fields to be disabled for all users. Cancelled date field will only show if the application was cancelled. 
- [x] Notes can only be edited by an admin user. Notes should only be displayed if there are notes made by the admin. 
- [x] Current tests do not test form well (at all). Add some more tests.
- [X] Make a show page for the form where none of the fields are editable.

### PR DESCRIPTION
**Pull request by calee14**
# Task
- [x] The Rider Application Form had two fields: Application Id and Applicant Id. This implementation was wrong and should only have one field for ID which is the rider application ID. This ID can be found in the Rider Application Entities file. 
- [x] The email field the in the form should be auto populated with the current user's email. This was not the case prior.
- [x] Must fix the date update, applied, and cancelled fields to be disabled for all users. Cancelled date field will only show if the application was cancelled. 
- [x] Notes can only be edited by an admin user. Notes should only be displayed if there are notes made by the admin. 
- [x] Current tests do not test form well (at all). Add some more tests.

In this PR, I fixed the Rider Application Form to match the requirements from the EPIC. 

I also added code that fixed the storybook for the form. Prior, storybooks did not display the different states the form can be in. I added a storybook for when a user is creating a new application, when a user is editing their application, and one for an admin editing an application.

For the RiderApplicationForm itself, I added the changes that were specified under the Task checklist. More importantly, I added code so that the form can access the currentUser object and check if the user was regular user or admin. This was important for implementing the requirements listed in the issue I linked to below. Having the currentUser object was also important for autofilling the email field in the form. 

Screen Shot 2024-02-23 at 5 11 13 PM

Screen Shot 2024-02-23 at 5 10 48 PM

Screen Shot 2024-02-23 at 5 12 19 PM

Screen Shot 2024-02-28 at 7 23 50 PM

Closes #22

### CODE REVIEW

**Review by Rytuose — APPROVED** [review]
LGTM

**Review by cydthe — DISMISSED** [review]
LGTM

**Review by Rytuose — APPROVED** [review]
LGTM

**Comment by shamitagurusu** [comment]
LGTM 👍

**Review by shamitagurusu — APPROVED** [review]

**Review by Aasish-Virjala — APPROVED** [review]
LGTM!

**Pull request merged**
