### PR TITLE
Added Driver Availability Edit Page and Tests

### LINKED ISSUE #18: DriverAvailability: Edit Page

### PR DESCRIPTION
**Pull request by Rytuose**
In this PR, we added the driver availability edit page and related tests.

Edit page without PUT endpoint implemented
DriverAvailabilityEdit

Closes #18

### CODE REVIEW

**Review by cydthe — APPROVED** [review]
LGTM

**Review by cydthe — APPROVED** [review]
LGTM

**Review by wzqd — APPROVED** [review]
LGTM

**Review by andrewpengucsb — COMMENTED** [review]
LGTM rest merged in #33

**Review by andrewpengucsb — APPROVED** [review]

**Pull request merged**
