### PR TITLE
feat: add driverAvailability entity and driverAvailabilityFixtures an…

### LINKED ISSUE #16: Driver Availability: DriverAvailability database and fixtures
### Database record and fixtures

- [x] There is an `@Entity` called DriverAvailability with fields: `Long id`, (type depends) `driverId`, `String day`, `String startTime`, `String endTime`, `String notes`.
- [x] There is a `@Repository` called `DriverAvailabilityRepository`.
- [x] There is a fixtures file `driverAvailabilityFixtures.js`.

### PR DESCRIPTION
**Pull request by JosephLiCodes**
In this PR, we added the driverAvailability entity that holds the information for a driver availability entry as well as driverAvailability fixtures for testing.

### Database record and fixtures for driverAvailability

- [x] There is an `@Entity` called DriverAvailability with fields: `Long id`, (type depends) `driverId`, `String day`, `String startTime`, `String endTime`, `String notes`.
- [x] There is a `@Repository` called `DriverAvailabilityRepository`.
- [x] There is a fixtures file `driverAvailabilityFixtures.js`.

Closes #16

### CODE REVIEW

**Review by calee14 — APPROVED** [review]
LGTM

**Comment by andrewpengucsb** [comment]
Please update the description with a bit more detail, and tag the issue that this closes

**Review by Aasish-Virjala — DISMISSED** [review]
Check Andrews comment earlier

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
