### PR TITLE
DriverAvailabilityCreate Page and Stories

### LINKED ISSUE #19: DriverAvailability: Create Page

### PR DESCRIPTION
**Pull request by cydthe**
In this PR, we added a driverAvailability create page to allow drivers to put in their availability.
image
closes #19

### CODE REVIEW

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]
Please update PR description with info and images

Also put the stories file into a dedicated DriverAvailability folder like in #38

**Comment by cydthe** [comment]
Adding driverAvailability create page 
Screenshot 2024-03-12 at 5 45 57 PM

**Review by Rytuose — APPROVED** [review]
LGTM

**Review by Rytuose — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Review by Rytuose — APPROVED** [review]
LGTM

**Pull request merged**
