### PR TITLE
Driver Availability: Added Driver Availability Form and Tests

### LINKED ISSUE #10: Driver Availability: DriverAvailabilityForm
### 3rd issue: DriverAvailabilityForm

- [ ] There is a react component `DriverAvailabilityForm` that is suitable for use on the pages described in the acceptance criteria
- [ ] There are storybook entries

### PR DESCRIPTION
**Pull request by Rytuose**
Added the form for Driver Availability and associated tests. 
The form can be viewed on this pull request's storybook: 
https://ucsb-cs156-w24.github.io/proj-gauchoride-w24-7pm-3/prs/34/storybook

Invalid Inputs:
DriverAvailabilityFormErrors

DriverAvailabilityFormErrors2

Valid Inputs:
DriverAvailabilityFormGood

Closes #10

### CODE REVIEW

**Review by wzqd — DISMISSED** [review]
LGTM

**Review by cydthe — DISMISSED** [review]
LGTM

**Review by cydthe — APPROVED** [review]
LGTM

**Review by wzqd — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM, other files were merged as part of a separate PR

Points were assigned to #33

**Review by wzqd — APPROVED** [review]
The form storybook LGTM

**Pull request merged**
